apiVersion: v1
kind: Secret
metadata:
  name: emqx-admin
type: Opaque
stringData:
  username: admin
  password: admin-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: emqx-mqtt-users
type: Opaque
stringData:
  controller_username: controller
  controller_password: controller-secret
  bootstrap_username: bootstrap
  bootstrap_password: bootstrap-secret
