apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  type: ClusterIP
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
    - name: mqtts
      port: 8883
      targetPort: mqtts
    - name: dashboard
      port: 18083
      targetPort: dashboard
  selector:
    app.kubernetes.io/name: emqx

---
apiVersion: v1
kind: Service
metadata:
  name: emqx-external
spec:
  type: ClusterIP
  ports:
    - name: mqtts
      port: 8883
      targetPort: mqtts
    - name: mqtt-bootstrap
      port: 1883
      targetPort: mqtt
  selector:
    app.kubernetes.io/name: emqx
