apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edgeguardian

resources:
  - namespace.yaml
  - postgres
  - keycloak
  - minio
  - loki
  - grafana
  - pki
  - emqx
  - controller

labels:
  - pairs:
      app.kubernetes.io/part-of: edgeguardian
    includeSelectors: false
    includeTemplates: true
