apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    app.kubernetes.io/name: controller
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8443
      targetPort: http
  selector:
    app.kubernetes.io/name: controller

---
apiVersion: v1
kind: Service
metadata:
  name: edgeguardian-controller
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/exposure: external
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8443
      targetPort: http
  selector:
    app.kubernetes.io/name: controller
