apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-root
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: edgeguardian-broker-ca
spec:
  isCA: true
  commonName: EdgeGuardian Broker CA
  secretName: edgeguardian-broker-ca-secret
  duration: 87600h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-root
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: edgeguardian-broker-ca
spec:
  ca:
    secretName: edgeguardian-broker-ca-secret
