apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-theme-edgeguardian
  labels:
    {{- include "edgeguardian.componentLabels" (dict "ctx" . "component" "keycloak") | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/theme/login/*" }}
{{- if not (hasSuffix "/" $path) }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-theme-edgeguardian-css
  labels:
    {{- include "edgeguardian.componentLabels" (dict "ctx" . "component" "keycloak") | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/theme/login/resources/css/*" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
