logging:
  level:
    root: INFO
    com.edgeguardian: DEBUG
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

edgeguardian:
  controller:
    loki:
      url: ${EDGEGUARDIAN_CONTROLLER_LOKI_URL:http://localhost:3100}