server:
  port: 8443
  error:
    include-message: always

spring:
  application:
    name: edgeguardian-controller
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  threads:
    virtual:
      enabled: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    include:
      - db
      - mqtt
      - security
      - ca
      - logging
      - monitoring
      - storage

edgeguardian:
  controller:
    device:
      offline-threshold-minutes: 5