apiVersion: v1
kind: Service
metadata:
  name: emqx-external
spec:
  type: NodePort
  ports:
    - name: mqtts
      port: 8883
      targetPort: mqtts
      nodePort: 30883
    - name: mqtt-bootstrap
      port: 1883
      targetPort: mqtt
      nodePort: 31883
